# GitHub Dependabot configuration for Heimdall DNS Server
# This file configures automated dependency updates

version: 2
updates:
  # Update Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@roeej"
    assignees:
      - "@roeej"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    # Group updates to reduce PR noise
    groups:
      tokio-ecosystem:
        patterns:
          - "tokio*"
          - "tower*"
          - "hyper*"
      serde-ecosystem:
        patterns:
          - "serde*"
      test-dependencies:
        patterns:
          - "criterion*"
          - "proptest*"
        dependency-type: "development"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@roeej"
    assignees:
      - "@roeej"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Update Docker base images (if using Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@roeej"
    assignees:
      - "@roeej"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"