[package]
name = "heimdall"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
bitstream-io = "3.1.0"
bytes = "1.8"
crossbeam = "0.8"
dashmap = "6.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
parking_lot = "0.12"
thiserror = "2.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "dns_parsing"
harness = false
