version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "${DNS_PORT:-1053}:${DNS_PORT:-1053}/udp"
    environment:
      - MIX_ENV=prod
      - PHX_HOST=localhost
      - PORT=4000
      - DNS_PORT=${DNS_PORT:-1053}
      - SECRET_KEY_BASE=YourSecretKeyBaseHere
      - DATABASE_URL=ecto://postgres:postgres@db/heimdall
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=heimdall
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
