apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
data:
  heimdall.toml: |
    # Heimdall DNS Server Configuration
    # This ConfigMap is for reference and future use
    # Currently, configuration is passed via environment variables
    
    bind_addr = "{{ .Values.config.bindAddr }}"
    http_bind_addr = "{{ .Values.config.httpBindAddr }}"
    
    upstream_servers = [
      {{- range .Values.config.upstreamServers }}
      "{{ . }}",
      {{- end }}
    ]
    
    upstream_timeout = {{ .Values.config.upstreamTimeout }}
    max_cache_size = {{ .Values.config.cache.maxSize }}
    default_ttl = {{ .Values.config.cache.defaultTTL }}
    enable_caching = {{ .Values.config.cache.enabled }}
    
    {{- if .Values.persistence.enabled }}
    cache_file_path = "{{ .Values.config.cache.filePath }}"
    cache_save_interval = {{ .Values.config.cache.saveInterval }}
    {{- end }}
    
    enable_rate_limiting = {{ .Values.config.rateLimiting.enabled }}
    queries_per_second_per_ip = {{ .Values.config.rateLimiting.queriesPerSecondPerIP }}
    global_queries_per_second = {{ .Values.config.rateLimiting.globalQueriesPerSecond }}
    
    worker_threads = {{ .Values.config.workerThreads }}
    blocking_threads = {{ .Values.config.blockingThreads }}
    max_concurrent_queries = {{ .Values.config.maxConcurrentQueries }}
    max_retries = {{ .Values.config.maxRetries }}
    enable_parallel_queries = {{ .Values.config.enableParallelQueries }}
    
    {{- if .Values.config.dot.enabled }}
    # DNS-over-TLS Configuration
    enable_dot = true
    dot_bind_addr = "{{ .Values.config.dot.bindAddr }}"
    dot_cert_path = "{{ .Values.config.dot.tls.certPath }}"
    dot_key_path = "{{ .Values.config.dot.tls.keyPath }}"
    dot_auto_cert = {{ .Values.config.dot.tls.autoGenerate }}
    {{- end }}
    
    {{- if .Values.config.doh.enabled }}
    # DNS-over-HTTPS Configuration
    enable_doh = true
    doh_bind_addr = "{{ .Values.config.doh.bindAddr }}"
    doh_path = "{{ .Values.config.doh.path }}"
    doh_cert_path = "{{ .Values.config.doh.tls.certPath }}"
    doh_key_path = "{{ .Values.config.doh.tls.keyPath }}"
    doh_auto_cert = {{ .Values.config.doh.tls.autoGenerate }}
    {{- end }}