apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
  {{- with .Values.keel.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  # Limit the number of old ReplicaSets to keep
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- end }}
  {{- if .Values.minReadySeconds }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "heimdall.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "heimdall.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "heimdall.serviceAccountName" . }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns-udp
              containerPort: 1053
              protocol: UDP
            - name: dns-tcp
              containerPort: 1053
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            {{- if .Values.config.dot.enabled }}
            - name: dot
              containerPort: 853
              protocol: TCP
            {{- end }}
            {{- if .Values.config.doh.enabled }}
            - name: doh
              containerPort: 943
              protocol: TCP
            {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: HEIMDALL_BIND_ADDR
              value: {{ .Values.config.bindAddr | quote }}
            - name: HEIMDALL_HTTP_BIND_ADDR
              value: {{ .Values.config.httpBindAddr | quote }}
            - name: HEIMDALL_UPSTREAM_SERVERS
              value: {{ join "," .Values.config.upstreamServers | quote }}
            - name: HEIMDALL_UPSTREAM_TIMEOUT
              value: {{ .Values.config.upstreamTimeout | quote }}
            - name: HEIMDALL_MAX_CACHE_SIZE
              value: {{ .Values.config.cache.maxSize | quote }}
            - name: HEIMDALL_DEFAULT_TTL
              value: {{ .Values.config.cache.defaultTTL | quote }}
            - name: HEIMDALL_ENABLE_CACHING
              value: {{ .Values.config.cache.enabled | quote }}
            - name: HEIMDALL_CACHE_SAVE_INTERVAL
              value: {{ .Values.config.cache.saveInterval | quote }}
            {{- if .Values.persistence.enabled }}
            - name: HEIMDALL_CACHE_FILE_PATH
              value: {{ .Values.config.cache.filePath | quote }}
            {{- end }}
            - name: HEIMDALL_ENABLE_RATE_LIMITING
              value: {{ .Values.config.rateLimiting.enabled | quote }}
            - name: HEIMDALL_QUERIES_PER_SECOND_PER_IP
              value: {{ .Values.config.rateLimiting.queriesPerSecondPerIP | quote }}
            - name: HEIMDALL_GLOBAL_QUERIES_PER_SECOND
              value: {{ .Values.config.rateLimiting.globalQueriesPerSecond | quote }}
            - name: HEIMDALL_WORKER_THREADS
              value: {{ .Values.config.workerThreads | quote }}
            - name: HEIMDALL_BLOCKING_THREADS
              value: {{ .Values.config.blockingThreads | quote }}
            - name: HEIMDALL_MAX_CONCURRENT_QUERIES
              value: {{ .Values.config.maxConcurrentQueries | quote }}
            - name: HEIMDALL_MAX_RETRIES
              value: {{ .Values.config.maxRetries | quote }}
            - name: HEIMDALL_ENABLE_PARALLEL_QUERIES
              value: {{ .Values.config.enableParallelQueries | quote }}
            {{- if .Values.config.dot.enabled }}
            - name: HEIMDALL_ENABLE_DOT
              value: "true"
            - name: HEIMDALL_DOT_BIND_ADDR
              value: {{ .Values.config.dot.bindAddr | quote }}
            - name: HEIMDALL_DOT_CERT_PATH
              value: {{ .Values.config.dot.tls.certPath | quote }}
            - name: HEIMDALL_DOT_KEY_PATH
              value: {{ .Values.config.dot.tls.keyPath | quote }}
            - name: HEIMDALL_DOT_AUTO_CERT
              value: {{ .Values.config.dot.tls.autoGenerate | quote }}
            {{- end }}
            {{- if .Values.config.doh.enabled }}
            - name: HEIMDALL_ENABLE_DOH
              value: "true"
            - name: HEIMDALL_DOH_BIND_ADDR
              value: {{ .Values.config.doh.bindAddr | quote }}
            - name: HEIMDALL_DOH_PATH
              value: {{ .Values.config.doh.path | quote }}
            - name: HEIMDALL_DOH_CERT_PATH
              value: {{ .Values.config.doh.tls.certPath | quote }}
            - name: HEIMDALL_DOH_KEY_PATH
              value: {{ .Values.config.doh.tls.keyPath | quote }}
            - name: HEIMDALL_DOH_AUTO_CERT
              value: {{ .Values.config.doh.tls.autoGenerate | quote }}
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: HEIMDALL_REDIS_URL
              {{- if .Values.redis.auth.enabled }}
              value: "redis://:$(REDIS_PASSWORD)@{{ include "heimdall.fullname" . }}-redis:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "heimdall.fullname" . }}-redis-secret
                  key: redis-password
              {{- else }}
              value: "redis://{{ include "heimdall.fullname" . }}-redis:6379"
              {{- end }}
            - name: HEIMDALL_REDIS_ENABLED
              value: "true"
            {{- end }}
            # Cluster discovery environment variables
            - name: HEIMDALL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HEIMDALL_SERVICE_NAME
              value: {{ include "heimdall.fullname" . }}
            - name: HEIMDALL_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HEIMDALL_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: cache
              mountPath: /cache
            {{- end }}
            {{- if .Values.blocklistPersistence.enabled }}
            - name: blocklist
              mountPath: /heimdall/blocklists
            {{- end }}
            - name: tmp
              mountPath: /tmp
            {{- if or .Values.config.dot.enabled .Values.config.doh.enabled }}
            - name: tls
              mountPath: /tls
              {{- if not (or .Values.config.dot.tls.autoGenerate .Values.config.doh.tls.autoGenerate) }}
              readOnly: true
              {{- end }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "heimdall.fullname" . }}-cache
        {{- end }}
        {{- if .Values.blocklistPersistence.enabled }}
        - name: blocklist
          persistentVolumeClaim:
            {{- if .Values.blocklistPersistence.existingClaim }}
            claimName: {{ .Values.blocklistPersistence.existingClaim }}
            {{- else }}
            claimName: {{ include "heimdall.fullname" . }}-blocklist
            {{- end }}
        {{- end }}
        - name: tmp
          emptyDir: {}
        {{- if or .Values.config.dot.enabled .Values.config.doh.enabled }}
        - name: tls
          {{- if or .Values.config.dot.tls.autoGenerate .Values.config.doh.tls.autoGenerate }}
          emptyDir: {}
          {{- else }}
          secret:
            secretName: {{ include "heimdall.fullname" . }}-tls
          {{- end }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}