{{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . }}-redis-secret
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{- if .Values.redis.auth.existingSecret }}
  # Using existing secret
  {{- else }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}