apiVersion: v1
kind: Service
metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if hasKey .Values.service "publishNotReadyAddresses" }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  {{- end }}
  ports:
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns-udp
      protocol: {{ .Values.service.dnsProtocol }}
      name: dns-udp
    - port: {{ .Values.service.dnsTcpPort }}
      targetPort: dns-tcp
      protocol: {{ .Values.service.dnsTcpProtocol }}
      name: dns-tcp
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: {{ .Values.service.httpProtocol }}
      name: http
  selector:
    {{- include "heimdall.selectorLabels" . | nindent 4 }}