apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall-dns
  namespace: argocd
  annotations:
    # Enable automatic image updates
    argocd-image-updater.argoproj.io/image-list: heimdall=ghcr.io/roeej/heimdall
    argocd-image-updater.argoproj.io/heimdall.update-strategy: latest
    argocd-image-updater.argoproj.io/heimdall.allow-tags: regexp:^main-.*$|^latest$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/RoeeJ/heimdall
    targetRevision: HEAD
    path: helm/heimdall
    helm:
      values: |
        image:
          repository: ghcr.io/roeej/heimdall
          tag: latest
          pullPolicy: Always
        
        replicaCount: 3
        
        service:
          type: LoadBalancer
          annotations: {}
        
        config:
          cache:
            enabled: true
            maxSize: 10000
          rateLimiting:
            enabled: false
        
        persistence:
          enabled: true
          size: 2Gi
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        
        env:
          - name: RUST_LOG
            value: "heimdall=info,warn"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dns-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3  # Keep only 3 revisions in history